/**
 * THROWAWAY harness for wayfinder ticket #46 (map #38).
 * Runs the mermaid corpus through the real converter in a real browser and
 * writes a report. Not a regression test — it reports, it does not assert.
 */
import { test, expect } from "@playwright/test";
import { writeFileSync, mkdirSync } from "node:fs";
import { CORPUS } from "./corpus";

interface Result {
  status: string;
  ms?: number;
  skeletonCount?: number;
  convertedCount?: number;
  types?: Record<string, number>;
  isSingleImage?: boolean;
  fileCount?: number;
  elements?: Record<string, unknown>[];
  skeleton?: Record<string, unknown>[];
  error?: string;
  errorName?: string;
}

test("vocabulary conformance sweep", async ({ page }) => {
  test.setTimeout(15 * 60 * 1000);

  const consoleErrors: string[] = [];
  page.on("console", (m) => {
    if (m.type() === "error") consoleErrors.push(m.text());
  });
  page.on("pageerror", (e) => consoleErrors.push(`pageerror: ${e.message}`));

  await page.goto("/#/conformance");
  await page.waitForSelector(".excalidraw", { timeout: 60_000 });
  await page.waitForFunction(() => window.__conformance?.ready === true, {
    timeout: 60_000,
  });

  const results: Record<string, Result> = {};

  for (const c of CORPUS) {
    const before = consoleErrors.length;
    const r = (await page.evaluate(
      (m) => window.__conformance!.run(m),
      c.mermaid,
    )) as unknown as Result;
    const during = consoleErrors.slice(before);
    results[c.id] = {
      ...r,
      ...(during.length ? { console: during } : {}),
    } as Result;
  }

  // ---- drag-after-insert (question 3, programmatic half) -------------------
  const drag = await page.evaluate(() =>
    window.__conformance!.dragTest(
      "flowchart TD\nA[Start] --> B[Middle] --> C[End]",
      250,
      180,
    ),
  );

  mkdirSync("e2e/conformance/out", { recursive: true });
  writeFileSync(
    "e2e/conformance/out/raw.json",
    JSON.stringify({ results, drag }, null, 2),
  );

  // ---------------------------------------------------------------- report --
  const lines: string[] = [];
  lines.push("# Mermaid vocabulary conformance report");
  lines.push("");
  lines.push(
    "Generated by `e2e/conformance/vocabulary.playwright.ts` against " +
      "`@excalidraw/mermaid-to-excalidraw@2.2.2` in Chromium. Ticket #46, map #38.",
  );
  lines.push("");

  const groups = [...new Set(CORPUS.map((c) => c.group))];
  for (const g of groups) {
    lines.push(`## ${g}`);
    lines.push("");
    lines.push("| case | status | elements | types | flags | predicted (#) |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const c of CORPUS.filter((x) => x.group === g)) {
      const r = results[c.id]!;
      const types = r.types
        ? Object.entries(r.types)
            .map(([k, v]) => `${k}×${v}`)
            .join(" ")
        : "—";
      const flags: string[] = [];
      if (r.isSingleImage) flags.push("**SINGLE-IMAGE**");
      if (r.status === "throw") flags.push("**THREW**");
      if (r.convertedCount === 0) flags.push("empty");
      const arrows = (r.elements ?? []).filter((e) => e.type === "arrow");
      const unbound = arrows.filter((a) => !a.startBinding || !a.endBinding);
      if (arrows.length && unbound.length)
        flags.push(`${unbound.length}/${arrows.length} arrows unbound`);
      lines.push(
        `| \`${c.id}\` | ${r.status} | ${r.convertedCount ?? "—"} | ${types} | ${
          flags.join(", ") || "—"
        } | ${c.from ?? ""} ${c.expect} |`,
      );
    }
    lines.push("");
  }

  lines.push("## Errors thrown");
  lines.push("");
  const threw = CORPUS.filter((c) => results[c.id]!.status === "throw");
  if (threw.length === 0) {
    lines.push("None.");
  } else {
    for (const c of threw) {
      lines.push(`- \`${c.id}\` — \`${results[c.id]!.error}\``);
    }
  }
  lines.push("");

  lines.push("## Drag-after-insert");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(drag, null, 2).slice(0, 4000));
  lines.push("```");

  writeFileSync("e2e/conformance/out/report.md", lines.join("\n"));

  console.log(lines.join("\n"));

  expect(Object.keys(results)).toHaveLength(CORPUS.length);
});
