// Diagram Type Keywords for backwards scan detection
export const DIAGRAM_TYPE_KEYWORDS: Record<string, string[]> = {
  flowchart: ["flowchart", "flow chart", "flow", "process", "decision tree"],
  sequenceDiagram: [
    "sequence diagram",
    "sequencing",
    "sequence",
    "interactions",
    "message flow",
    "process order",
    "timeline",
    "call flow",
    "request response",
  ],
  classDiagram: [
    "class diagram",
    "class",
    "classes",
    "oop",
    "object oriented",
    "uml class",
    "inheritance",
  ],
};

// Direction Keywords for backwards scan detection
export const DIRECTION_KEYWORDS: Record<string, string[]> = {
  LR: [
    "left to right",
    "left-to-right",
    "horizontal",
    "lr",
    "left right",
    "l to r",
  ],
  RL: ["right to left", "right-to-left", "rtl", "right left", "r to l"],
  TD: ["top down", "top-down", "vertical", "td", "top bottom", "t to d"],
  BT: ["bottom to top", "bottom-to-top", "bt", "bottom top", "b to t"],
};

// Common words to filter from entity extraction
export const COMMON_FILTER = new Set([
  // Articles
  "a",
  "an",
  "the",
  // Conjunctions
  "and",
  "or",
  "but",
  "because",
  "so",
  // Prepositions
  "in",
  "on",
  "at",
  "to",
  "for",
  "of",
  "with",
  "by",
  "from",
  "as",
  "into",
  "through",
  // Pronouns
  "i",
  "me",
  "my",
  "you",
  "your",
  "he",
  "him",
  "his",
  "she",
  "her",
  "it",
  "its",
  "we",
  "us",
  "our",
  "they",
  "them",
  "their",
  // Common verbs
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "do",
  "does",
  "did",
  "will",
  "would",
  "can",
  "could",
  "should",
  "may",
  "might",
  // Diagram-related words
  "diagram",
  "flowchart",
  "graph",
  "sequence",
  "class",
  "node",
  "edge",
  "vertex",
  "link",
  "style",
  "flow",
  "chart",
  // Direction/orientation words (not entities)
  "left",
  "right",
  "up",
  "down",
  "top",
  "bottom",
  "horizontal",
  "vertical",
  "td",
  "lr",
  "rl",
  "bt",
  "up",
  "down",
  // Action words
  "create",
  "draw",
  "show",
  "make",
  "generate",
  "display",
  "get",
  "use",
  "go",
  "see",
  "wait",
]);
